##
## EPITECH PROJECT, 2024
## Makefile
## File description:
## Makefile
##

SRC =	*.c

NAME =	102architect

all :	$(NAME)

$(NAME) :	$(SRC)
	gcc -o $(NAME) $(SRC) -lm
clean :
	rm -f *~
	rm -f *.o

fclean :
	rm -f $(NAME)

re : fclean all
