##
## EPITECH PROJECT, 2024
## makefile
## File description:
## makefile
##

SRC     =       *.c

NAME    =       103cipher

all:
	gcc $(SRC) -o $(NAME) -lm

clean:
	rm -f *#
	rm -f *~

fclean:
	rm -f $(NAME)
	rm -f *#
	rm -f *~
	clear

re:     fclean all
