#!/usr/bin/env ruby
##
## EPITECH PROJECT, 2025
## 110borwein
## File description:
## 110borwein
##

# #{d} pour afficher des variables

def usage
  puts "USAGE"
  puts "    ./110borwein n"
  print "\n"
  puts "DESCRIPTION"
  puts "    n   constant defining the integral to be computed"
end

def borwein_function(n, x)
  result = 1.0

  if x == 0
    return result
  end
  for k in 0..n
    denom = x / (2.0 * k + 1.0)
      result *= Math.sin(denom) / denom
  end
  return result
end

def midpoint(n)
  gn = 5000.to_f / 10000.to_f
  sum = 0.0
  a = 0.0
  b = 0.0
  for k in 0...10000
    a = k * gn
    b = (k + 1) * gn
    sum = sum + ((b - a) * borwein_function(n, (a + b) / 2.0))
  end
  return sum
end

def trapezoidal(n)
  gn = 10000.0
  sum1 = 0.0
  dx = 5000.0 / gn

  for k in 0...gn
    a = dx * k
    b = (k + 1) * dx
    sum1 += (b - a) / 2.0 * (borwein_function(n, a) + borwein_function(n, b))
  end
  return sum1
end

def simpson(n)
  gn = 5000.0 / 10000.0
  sum2 = 0.0

  for l in 0...10000
    a = l * gn
    b = (l + 1) * gn
    sum2 += (b - a) / 6.0 * (borwein_function(n, a) + 4 * borwein_function(n, (a + b) / 2) + borwein_function(n, b))
  end
  return sum2
end

def calc(x)
  a = 0.0
  b = 5000.0
  sum = midpoint(x)
  puts("Midpoint:")
  printf("I%d = %.10f\n", x, sum)
  dif = (Math::PI / 2.0 - sum).abs
  printf("diff = %.10f\n\n", dif)
  tra = trapezoidal(x)
  puts("Trapezoidal:")
  printf("I%d = %.10f\n", x, tra)
  dif1 = (Math::PI / 2.0 - tra).abs
  printf("diff = %.10f\n\n", dif1)
  simp = simpson(x)
  puts("Simpson:")
  printf("I%d = %.10f\n", x, simp)
  dif2 = (Math::PI / 2.0 - simp).abs
  printf("diff = %.10f\n", dif2)
end

def calc_error(x)
  if x.to_i > 5000
    exit 84
  else
    x1 = x.to_i
    calc(x1)
  end
end


def print_usage
  if ARGV[0] == '-h'
    usage
  else
    if ARGV[0].size == 0
      exit 84
    end
    if ARGV[0].to_i.to_s != ARGV[0] || ARGV[0][0] == '-'
      exit 84
    else
      calc_error(ARGV[0])
    end
  end
end


def main
  if ARGV.length == 1
    print_usage
  else
    return 84
  end
end

if main == 84
  exit 84
end
